name: "HCL AppScan CodeSweep" 
on: 
  push: 
    branches: 
    - master 
jobs: 
  scan: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
        with: 
          fetch-depth: 0 
      - name: Run AppScan CodeSweep 
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2 
        with: 
          asoc_key: ${{secrets.ASOC_KEY}} 
          asoc_secret: ${{secrets.ASOC_SECRET}} 
      - name: Publish issues to ASoC 
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2 
        with: 
          asoc_key: ${{secrets.ASOC_KEY}} 
          asoc_secret: ${{secrets.ASOC_SECRET}} 
          publish_on_merge: true 
          application_id: e106b91f-b68f-4c42-aa92-cbc66ba07efa 
    env:  
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
